apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-prod
spec:
  acme:
    email: '${cloudflare-email}' 
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-prod-account-key
    solvers:
    - dns01:
        cloudflare:
          email: '${cloudflare-email}' 
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key